"""Initial schema

Revision ID: 7f69485203fb
Revises: 
Create Date: 2026-09-12 18:04:04.963043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '7f69485203fb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        "CREATE EXTENSION IF NOT EXISTS vector"
    )    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('selected_tool', sa.String(length=255), nullable=True),
    sa.Column('tool_used', sa.Boolean(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('evaluation_score', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('approval_id', sa.String(length=36), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_approval_id'), 'agent_runs', ['approval_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_id'), 'agent_runs', ['id'], unique=False)
    op.create_index(op.f('ix_agent_runs_run_id'), 'agent_runs', ['run_id'], unique=True)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_table('agent_traces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('node_name', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_traces_event_type'), 'agent_traces', ['event_type'], unique=False)
    op.create_index(op.f('ix_agent_traces_id'), 'agent_traces', ['id'], unique=False)
    op.create_index(op.f('ix_agent_traces_node_name'), 'agent_traces', ['node_name'], unique=False)
    op.create_index(op.f('ix_agent_traces_run_id'), 'agent_traces', ['run_id'], unique=False)
    op.create_index(op.f('ix_agent_traces_status'), 'agent_traces', ['status'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approval_id', sa.String(length=36), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('arguments', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_approval_id'), 'approval_requests', ['approval_id'], unique=True)
    op.create_index(op.f('ix_approval_requests_id'), 'approval_requests', ['id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('approval_id', sa.String(length=36), nullable=True),
    sa.Column('tool_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_approval_id'), 'audit_events', ['approval_id'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_id'), 'audit_events', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('evaluation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('suite_id', sa.String(length=36), nullable=True),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('actual_tool', sa.String(length=255), nullable=True),
    sa.Column('actual_approval_required', sa.Boolean(), nullable=False),
    sa.Column('evaluation_score', sa.Integer(), nullable=True),
    sa.Column('evaluation_feedback', sa.Text(), nullable=False),
    sa.Column('checks', sa.Text(), nullable=False),
    sa.Column('failed_checks', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_results_case_id'), 'evaluation_results', ['case_id'], unique=False)
    op.create_index(op.f('ix_evaluation_results_evaluation_id'), 'evaluation_results', ['evaluation_id'], unique=True)
    op.create_index(op.f('ix_evaluation_results_id'), 'evaluation_results', ['id'], unique=False)
    op.create_index(op.f('ix_evaluation_results_run_id'), 'evaluation_results', ['run_id'], unique=False)
    op.create_index(op.f('ix_evaluation_results_status'), 'evaluation_results', ['status'], unique=False)
    op.create_index(op.f('ix_evaluation_results_suite_id'), 'evaluation_results', ['suite_id'], unique=False)
    op.create_table('test_suite_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suite_run_id', sa.String(length=36), nullable=False),
    sa.Column('suite_id', sa.String(length=36), nullable=False),
    sa.Column('suite_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_tests', sa.Integer(), nullable=False),
    sa.Column('passed_tests', sa.Integer(), nullable=False),
    sa.Column('failed_tests', sa.Integer(), nullable=False),
    sa.Column('pass_rate', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_suite_runs_id'), 'test_suite_runs', ['id'], unique=False)
    op.create_index(op.f('ix_test_suite_runs_status'), 'test_suite_runs', ['status'], unique=False)
    op.create_index(op.f('ix_test_suite_runs_suite_id'), 'test_suite_runs', ['suite_id'], unique=False)
    op.create_index(op.f('ix_test_suite_runs_suite_run_id'), 'test_suite_runs', ['suite_run_id'], unique=True)
    op.create_table('test_suites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suite_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_suites_id'), 'test_suites', ['id'], unique=False)
    op.create_index(op.f('ix_test_suites_status'), 'test_suites', ['status'], unique=False)
    op.create_index(op.f('ix_test_suites_suite_id'), 'test_suites', ['suite_id'], unique=True)
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3072), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_id'), 'document_chunks', ['id'], unique=False)
    op.create_table('test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('test_suite_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('input_prompt', sa.Text(), nullable=False),
    sa.Column('expected_tool', sa.String(length=255), nullable=True),
    sa.Column('expected_approval_required', sa.Boolean(), nullable=True),
    sa.Column('min_evaluation_score', sa.Integer(), nullable=True),
    sa.Column('expected_response_contains', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['test_suite_id'], ['test_suites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_cases_case_id'), 'test_cases', ['case_id'], unique=True)
    op.create_index(op.f('ix_test_cases_id'), 'test_cases', ['id'], unique=False)
    op.create_index(op.f('ix_test_cases_test_suite_id'), 'test_cases', ['test_suite_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_cases_test_suite_id'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_id'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_case_id'), table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_index(op.f('ix_document_chunks_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_test_suites_suite_id'), table_name='test_suites')
    op.drop_index(op.f('ix_test_suites_status'), table_name='test_suites')
    op.drop_index(op.f('ix_test_suites_id'), table_name='test_suites')
    op.drop_table('test_suites')
    op.drop_index(op.f('ix_test_suite_runs_suite_run_id'), table_name='test_suite_runs')
    op.drop_index(op.f('ix_test_suite_runs_suite_id'), table_name='test_suite_runs')
    op.drop_index(op.f('ix_test_suite_runs_status'), table_name='test_suite_runs')
    op.drop_index(op.f('ix_test_suite_runs_id'), table_name='test_suite_runs')
    op.drop_table('test_suite_runs')
    op.drop_index(op.f('ix_evaluation_results_suite_id'), table_name='evaluation_results')
    op.drop_index(op.f('ix_evaluation_results_status'), table_name='evaluation_results')
    op.drop_index(op.f('ix_evaluation_results_run_id'), table_name='evaluation_results')
    op.drop_index(op.f('ix_evaluation_results_id'), table_name='evaluation_results')
    op.drop_index(op.f('ix_evaluation_results_evaluation_id'), table_name='evaluation_results')
    op.drop_index(op.f('ix_evaluation_results_case_id'), table_name='evaluation_results')
    op.drop_table('evaluation_results')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_audit_events_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_approval_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_approval_requests_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_approval_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_agent_traces_status'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_run_id'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_node_name'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_id'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_event_type'), table_name='agent_traces')
    op.drop_table('agent_traces')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_run_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_approval_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
